### ISSUE TITLE
Made for Teensy 4/4.1?

### ISSUE THREAD

**Issue by AllisonHaackNDTS** [luni64/EncSim#3]
Hello!

I noticed that you have the beginning of code for this project for the Teensy 4 and 4.1 boards in the config files. I've tried to run this on my 4.1 board with no luck. If you have any suggestions on how to incorporate the 4.1 into this project, please let me know!

**Comment by luni64** [comment]
No, this is not prepared for T4x at all. But it shouldn't be too difficult to port. If it is not too urgent I can do this next weekend or so.

**Comment by AllisonHaackNDTS** [comment]
That would be lovely! Thank you for looking into it!

**Comment by luni64** [comment]
I updated the library to be compatible to T4.1.  https://github.com/luni64/EncSim/releases

This required a change from TeensyDelay to the [TeensyTimerTool](https://github.com/luni64/TeensyTimerTool) as provider for the underlying timers. Make sure to have this library installed before compiling EncSim. 

Let me know if you face problems. Did't do very extensive testing....

**Comment by AllisonHaackNDTS** [comment]
Thank you so much! I’ll give it a try this afternoon and let you know!
