### ISSUE TITLE
Double Encoder in parrallel ?

### ISSUE THREAD

**Issue by ghost** [luni64/EncSim#4]
Hi thanks for this project it help me a lot on a unit test on Industrial Ultrasonic Equipment validation.
Is it possible to define 2 EncSim like this :

`EncSim simulator(0,1);`
`EncSim simulator2(3,4);`

and apply different configuration (freq, period) on each ?

I hope my request is clear for you

Thanks a lot 
M.GIRARD

**Comment by luni64** [comment]
Not yet but this is easily fixed. However, I can't work on it until the weekend

**Comment by luni64** [comment]
See version v2.3.0. You should be able to generate up to 4 simulator objects now.

**Comment by ghost** [comment]
Thanks it works great !
